- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Install dependencies
  command: npm install
  args:
    chdir: /home/ubuntu/backend

- name: copy file
  become: true
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Unarchives the compressed artifact file
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Use pm2 to run backend
  command: pm2 start dist/main.js --name "backend" -i max
  args:
    chdir: /home/ubuntu/backend