- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Install dependencies
  command: npm install
  args:
    chdir: /home/ubuntu/backend

- name: copy file
  become: true
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: uncompress the copied file
  shell: |
    cd /home/ubuntu/backend
    tar xzvf artifact.tar.gz
    pwd

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/backend